apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    chart: appotapay
data:
  default.conf: |-
    server {
      listen 0.0.0.0:80;
      index index.php index.html;
      root /var/www/code/public;
      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;
      location / {
          try_files $uri /index.php?$args;
      }
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass phpfpm-service:9000;
          fastcgi_index index.php;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO $fastcgi_path_info;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-configmap
  labels:
    chart: appotapay
data:
  .env: |-
    APP_NAME=Laravel
    APP_ENV=local
    APP_KEY=base64:M4/M/QS2+NosHO4dhl5Bcp4aJJQnZkfeb+aiS3S/r5I=
    APP_DEBUG=true
    APP_URL=http://localhost
    LOG_CHANNEL=stack
    LOG_DEPRECATIONS_CHANNEL=null
    LOG_LEVEL=debug
    DB_CONNECTION=mysql
    DB_HOST=127.0.0.1
    DB_PORT=3306
    DB_DATABASE=laravel
    DB_USERNAME=root
    DB_PASSWORD=
    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    FILESYSTEM_DISK=local
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120
    MEMCACHED_HOST=127.0.0.1
    REDIS_HOST=127.0.0.1
    REDIS_PASSWORD=null
    REDIS_PORT=6379
    MAIL_MAILER=smtp
    MAIL_HOST=mailpit
    MAIL_PORT=1025
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null
    MAIL_FROM_ADDRESS="hello@example.com"
    MAIL_FROM_NAME="${APP_NAME}"
    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=
    AWS_USE_PATH_STYLE_ENDPOINT=false
    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_HOST=
    PUSHER_PORT=443
    PUSHER_SCHEME=https
    PUSHER_APP_CLUSTER=mt1
    VITE_APP_NAME="${APP_NAME}"
    VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    VITE_PUSHER_HOST="${PUSHER_HOST}"
    VITE_PUSHER_PORT="${PUSHER_PORT}"
    VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
    VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  labels:
    chart: appotapay
data:
  MARIADB_USER: "tungbt"
  MARIADB_PASSWORD: "12345678"
  MARIADB_ROOT_PASSWORD: "12345678"
  MARIADB_ROOT_HOST: "%"