---
- name: Iptables
  hosts: all

  tasks:
    # This will apply to all loaded/active IPv4 tables.
    - name: Save current state of the firewall in system file
      community.general.iptables_state:
        state: saved
        path: /etc/sysconfig/iptables

    # This will apply only to IPv6 filter table.
    - name: save current state of the firewall in system file
      community.general.iptables_state:
        ip_version: ipv6
        table: filter
        state: saved
        path: /etc/iptables/rules.v6